# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

polyseries_mean_single <- function(size, alpha, sigma) {
    .Call('_HubbellGLM_polyseries_mean_single', PACKAGE = 'HubbellGLM', size, alpha, sigma)
}

polyseries_var_single <- function(size, alpha, sigma) {
    .Call('_HubbellGLM_polyseries_var_single', PACKAGE = 'HubbellGLM', size, alpha, sigma)
}

polyseries_mean_grid <- function(points_grid, size, alpha, sigma) {
    .Call('_HubbellGLM_polyseries_mean_grid', PACKAGE = 'HubbellGLM', points_grid, size, alpha, sigma)
}

polyseries_var_grid <- function(points_grid, size, alpha, sigma) {
    .Call('_HubbellGLM_polyseries_var_grid', PACKAGE = 'HubbellGLM', points_grid, size, alpha, sigma)
}

polyseries_mean <- function(size, alpha, sigma) {
    .Call('_HubbellGLM_polyseries_mean', PACKAGE = 'HubbellGLM', size, alpha, sigma)
}

polyseries_var <- function(size, alpha, sigma) {
    .Call('_HubbellGLM_polyseries_var', PACKAGE = 'HubbellGLM', size, alpha, sigma)
}

polyseries_meanvar_fast <- function(size, alpha, sigma, nthreads = 1L) {
    .Call('_HubbellGLM_polyseries_meanvar_fast', PACKAGE = 'HubbellGLM', size, alpha, sigma, nthreads)
}

polyseries_mean_fast <- function(size, alpha, sigma, nthreads = 1L) {
    .Call('_HubbellGLM_polyseries_mean_fast', PACKAGE = 'HubbellGLM', size, alpha, sigma, nthreads)
}

inv_polyseries_fast <- function(mu_target, size, sigma, tol = 1e-10, maxit = 100L, nthreads = 1L) {
    .Call('_HubbellGLM_inv_polyseries_fast', PACKAGE = 'HubbellGLM', mu_target, size, sigma, tol, maxit, nthreads)
}

inv_mean_dp_fast <- function(mu_target, size, tol = 1e-10, maxit = 100L, nthreads = 1L) {
    .Call('_HubbellGLM_inv_mean_dp_fast', PACKAGE = 'HubbellGLM', mu_target, size, tol, maxit, nthreads)
}

DPspecies_cpp <- function(alpha, size) {
    .Call('_HubbellGLM_DPspecies_cpp', PACKAGE = 'HubbellGLM', alpha, size)
}

lastirling1 <- function(n) {
    .Call('_HubbellGLM_lastirling1', PACKAGE = 'HubbellGLM', n)
}

lastirlings1 <- function(n) {
    .Call('_HubbellGLM_lastirlings1', PACKAGE = 'HubbellGLM', n)
}

rarefy_C <- function(freq, n, K, verbose) {
    .Call('_HubbellGLM_rarefy_C', PACKAGE = 'HubbellGLM', freq, n, K, verbose)
}

